- client/src/views/pages/survey.js
แก้ตัวแปร ปิดส่งคำตอบ ajax post
> revise variable and send answer

- client/src/views/pages/survey.js
auto load form from api + auto load answer from api
> auto load form from api + auto load answer from api

- client/src/views/pages/login.js
- client/src/views/pages/survey.js
- client/src/views/pages/surveyresult.js
edit login page and edit bug popup roommate
> edit login page and edit bug popup roomate

- client/src/layouts/components/navbar/navbar.js
- client/src/services/AuthService.js
- client/src/views/pages/SurveyCreator.js
- client/src/views/pages/survey.js
- client/src/views/pages/surveyresult.js
- client/src/views/pages/userProfile.js
change api for authentication redirect to login when backend return false
> change api for authentication

- client/src/services/AuthService.js
- client/src/views/pages/SurveyCreator.js
- client/src/views/pages/survey.js
- client/src/views/pages/surveyresult.js
- client/src/views/pages/userProfile.js
fix redirect when token is expired and change redis server
> fix redirect when token is expired

- client/src/views/pages/login.js
- client/src/views/pages/survey.js
- client/src/views/pages/surveyresult.js
- client/src/views/pages/userProfile.js
fix bug ui sprint6 by pepsi and khuean#1
> fix bug ui sprint6 by pepsi and khuean#1

- client/src/layouts/components/footer/footer.js
- client/src/views/pages/error.js
- client/src/views/pages/login.js
- client/src/views/pages/surveyresult.js
survey page, login page , surveyresult page
> config bug from n'khuean

- client/src/views/pages/summary.js
- client/src/views/pages/surveyresult.js
เลือกห้อง ห้องเพื่อนต้องเปลี่ยนด้วย
> แก้ผลสำรวจบั๊คอาหาร ,แก้หน้าจัดการห้องพัก 

- .gitignore
- backend/app.js
- backend/components/gsurveys/admin/index.js
- backend/components/gsurveys/users/index.js
Initialise apis
* users
-  [GET] /v2/survey/users/question
-  [POST] /v2/survey/users/answers
* Admin
- [GET|POST] /v2/survey/admin/questions
- [GET] /v2/survey/admin/answers
> add users and admin api

- backend/components/helpers/mongodb.js
- backend/components/v2/admin/index.js
Add new APIs
* delete a survey, [DELETE] /api/v2/admin/survey
* rename a surrvey, [PUT] /api/v2/admin/survey
> support rename and delete a survey

- backend/components/v2/admin/index.js
- backend/package.json
New APIs Lists for managing results
* [POST] /api/v2/admin/results, save the result.
* [GET] /api/v2/admin/results/surveyid/:surveyid, read the results by survey id.
* [GET] /api/v2/admin/results/resultid,  read the result by result id.
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/6b6ee0dc6e93b44c5f7a)
> Initialize api

- backend/app.js
- backend/components/v2/admin/index.js
- backend/components/v2/admin/user.js
- backend/components/v2/auth/auth.js
- backend/components/v2/auth/index.js
- backend/package.json
Add Login API
* Login
[POST] /api/v2/auth/login
```
{
"username": "yourusername",
"password": "yourpassword"
}
```
* Get Profile
[GET] /api/v2/admin/users/profile
> add login API

- backend/config/production.conf-template.js
- scripts/mongo-export-csv.sh
For instance,
```bash
mongoexport -h 127.0.0.1 -p 27017 -d gsurvey -c result --type=csv --fields result.Q1,result.Q2,result.Q3
```
> Export data from mongodb to  csv file

- client/src/index.js
* enable google analytic tracking 
see statistics: https://analytics.google.com/
> enable google analytic tracking

- backend/components/helpers/mongodb.js
- backend/components/v2/admin/index.js
- backend/components/v2/auth/auth.js
- backend/components/v2/users/index.js
* add timestamp
* search with desc order
For an instance,
```json
{
"surveyid": "3",
"resultid": "31a74e16-cfd8-4911-9ab4-d8bbfcb88d08",
"userid": "1",
"result": {
"Q1": "yes",
"Q2": "No",
"Q3": "yes"
},
"version": "1",
"created_at": "2020-03-23T12:08:26.518Z",
"modified_at": "2020-03-23T12:08:26.518Z"
}
```
> add timestamp and search with desc order

- backend/start.sh
- client/start.sh
add script to start process by using pm2
```
client/start.sh
backend/start.sh
```
@sakulwan
> add start scripts by using pm2

- backend/components/helpers/mail.js
- backend/components/helpers/redis.js
- backend/components/v2/admin/index.js
- backend/components/v2/admin/user.js
- backend/components/v2/auth/auth.js
- backend/components/v2/users/index.js
- backend/components/v2/users/organization.js
- backend/components/v2/users/password.js
- backend/components/v2/users/register.js
- backend/config/production.conf.js
* change password 
* reset password
สามารถเปลี่ยน password จาก email ที่ส่งให้ไป
flow การทำงาน
```
กดลืมรหัส --> backend gen OTP สร้างเป็น URL ส่งไปใน email 
--> ผู้ใช้กด link ตามที่ส่งให้ไป --> ผู้ใช้ กรอก user pass ใหม่ --> fontend ส่ง user, pass, OTP ให้ backend --> ถ้าสำเร็จ redirect ไปหน้า login
```
ขอ OTP
POST /api/v2/users/otp
request
```json
{
"ref_code": "axFx",
"email": "narongsak.mala@gmail.com",
"return_url": "https://gsurvey.dga.or.th/pages/password/reset"
}
```
จะส่ง link (https://gsurvey.dga.or.th/pages/resetpassword?ref_code=0181&email=narongsak.mala@dga.or.th&otp=12345)
ผู้ใช้กรอก new password
POST /apt/v2/users/password/reset
```json
{
"ref_code": "axFx",
"otp": 	"ZgkNgKIdndq88uw4",
"email": "narongsak.mala@gmail.com",
"password": "4567"
"return_url": …
```
> add change and reset password

- backend/components/v2/admin/members.js
- backend/components/v2/auth/auth.js
* อนุมัติ / ไม่อนุมัติ
* ระงับ
* ลบ
----
| ชื่อผู้ใช้ | email | tel | approve or reject (descriptions)
---- 
API GET /api/v2/admin/members
response
```JSON
{
"success": true,
"code": 20000,
"desc": null,
"data": [
{
"user_id": 24,
"username": "narongsak.mala@gmail.com",
"prefix_name": "นาย",
"firstname": "Narongsak",
"lastname": "Mala",
"email": "narongsak.mala@gmail.com",
"mobile": "0817264466",
"office_phone": "",
"ext": "",
"min_name": "สำนักนายกรัฐมนตรี",
"dep_name": "สำนักงานปลัดสำนักนายกรัฐมนตรี",
"org_name": "สำนักงานปลัดสำนักนายกรัฐมนตรี",
"suspension_status": 0,
"approval_status": "approved",
"approved_by": null
},
{
"user_id": 36,
"username": "narongsak.mala@dga.or.th",
"prefix_name": "นาย",
"firstname": "Narongsak",
"lastname": "Mala",
"email": "narongsak.mala@dga.or.th", …
```
> add suspension, deletion and approval api

- backend/components/v2/auth/auth.js
ปรับการ authentication โดยการเช็ค reject, disable, delete flags
```
20000 = success
40103 = reject (ขออภัยบัญชีผู้ใช้งานของท่านไม่ได้รับการอนุมัติ)
40104 = disable (ขออภัยบัญชีผู้ใช้งานของท่านถูกระงับชั่วคราว)
40105 = delete (ไม่พบบัญชีผู้ใช้งาน)
40106 = waiting (บัญชีผู้ใช้อยู่ระหว่างการพิจารณาอนุมัติ)
40000 = invalid credential (user or password invalid)
500xx = internal system error
```
- ต้องมีการตรวจเช็ค flags ในการ login
- แสดงข้อความหน้า login ตาม error code ที่กำหนด
` กระทบกับ /api/v2/auth/login API `
> v2-backend-revise-error-code

- backend/components/helpers/mongodb.js
- backend/components/v2/users/index.js
Use insertOne instead of findAndReplaceOne method to increase performance
> use insertOne instead of findAndReplaceOne

- backend/components/v2/admin/members.js
change suspension flag to status 
example 
```json
"success": true,
"code": 20000,
"desc": null,
"data": [
{
"user_id": 24,
"username": "narongsak.mala@gmail.com",
"prefix_name": "นาย",
"firstname": "Narongsak",
"lastname": "Mala",
"email": "narongsak.mala@gmail.com",
"mobile": "0817264466",
"office_phone": "",
"ext": "",
"min_name": "สำนักนายกรัฐมนตรี",
"dep_name": "สำนักงานปลัดสำนักนายกรัฐมนตรี",
"org_name": "สำนักงานปลัดสำนักนายกรัฐมนตรี",
"approval_status": "approve",
"approved_by": "36",
"suspension_status": "disable"
},
{
"user_id": 40,
"username": "narongsak_mala@outlook.com",
"prefix_name": "นาย",
"firstname": "Narongsak",
"lastname": "Mala",
"email": "narongsak_mala@outlook.com",
"mobile": "0817264466",
"office_phone": "",
"ext": "",
"min_name": "สำนักนายกรัฐมนตรี",
"dep_name": …
```
> change suspension flag to status

- client/src/services/validateRegister.js
- client/src/views/pages/register.js
- client/src/views/pages/resetPassword.js
ปรับ password ให้มีเงื่อนไข
- มีตัวพิมพ์ใหญ่ อย่างน้อย 1 ตัว
- มีตัวพิมพ์เล็ก
- มีอย่างน้อย 8 ตัวอักษร
- มีตัวเลขอย่างน้อย 1 ตัว
> password condition, tooltips box

- backend/components/v2/admin/index.js
- backend/components/v2/admin/user.js
- backend/components/v2/users/index.js
- backend/components/v2/users/organization.js
- คำนำหน้า
- ชื่อ
- สกุล
- ตำแหน่ง
- email (แสดงอย่างเดียว)
- กระทรวง (แสดงอย่างเดียว)
- กรม (แสดงอย่างเดียว)
- หน่วยงาน (แสดงอย่างเดียว)
- มือถือ
- เบอร์สำนักงาน
- เบอร์ต่อภายใน
- role (แสดงอย่างเดียว)
----
GET /api/v2/users/prefixes
** response body **
```json
[
{"id": 1, "name": "นาย"},
{"id": 2, "name": "นาง"},
...
]
```
GET /api/v2/admin/profile
** response body **
```json
{
"success": true,
"code": 20000,
"desc": null,
"data": {
"prefix_id": 1,
"firstname": "Narongsak",
"lastname": "Mala",
"position": "",
"email": "narongsak.mala@dga.or.th",
"ministry": "สำนักนายกรัฐมนตรี",
"department": "สำนักงานปลัดสำนักนายกรัฐมนตรี",
"organization": "สำนักงานปลัดสำนักนายกรัฐมนตรี",
"mobile": "0817264466",
"office_phone": "",
"ext": "",
"role": "system admin"
}
}
```
POST /api/v2/admin/profile
** …
> add prefix, profile APIs

- backend/components/v2/email-templates/form.js
- backend/components/v2/users/password.js
- Fix bug for outlook email does not support background gradient CSS
> Fix bug for outlook email does not support background gradient CSS

- client/src/layouts/components/sidebar/sidemenu/sidemenu.js
- client/src/views/pages/resetPassword.js
- client/src/views/pages/userProfile.js
1. use react-from-hook for form change password
2. edit regex 
3. hide menu[1] for org admin role
> change password , bug reset password , bug side menu for org admin role

- client/src/index.js
- client/src/layouts/components/footer/footer.js
- client/src/layouts/components/navbar/navbar.js
- client/src/layouts/components/sidebar/sidebar.js
- client/src/layouts/components/sidebar/sidemenu/sidemenu.js
- client/src/services/UserAuth.js
- client/src/services/validateRegister.js
- client/src/views/pages/dashboard-all.js
- client/src/views/pages/dashboard-by-department.js
- client/src/views/pages/main.js
- client/src/views/pages/useForm.js
use eslint for detected warning and error
> remove warning and error on each page
